/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AccountFrozen = {
  mint: Address;
  account: Address;
  authority: Address;
};

export type AccountFrozenArgs = AccountFrozen;

export function getAccountFrozenEncoder(): FixedSizeEncoder<AccountFrozenArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["account", getAddressEncoder()],
    ["authority", getAddressEncoder()],
  ]);
}

export function getAccountFrozenDecoder(): FixedSizeDecoder<AccountFrozen> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["account", getAddressDecoder()],
    ["authority", getAddressDecoder()],
  ]);
}

export function getAccountFrozenCodec(): FixedSizeCodec<
  AccountFrozenArgs,
  AccountFrozen
> {
  return combineCodec(getAccountFrozenEncoder(), getAccountFrozenDecoder());
}
