/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AddressUnblacklisted = {
  mint: Address;
  wallet: Address;
  authority: Address;
};

export type AddressUnblacklistedArgs = AddressUnblacklisted;

export function getAddressUnblacklistedEncoder(): FixedSizeEncoder<AddressUnblacklistedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["wallet", getAddressEncoder()],
    ["authority", getAddressEncoder()],
  ]);
}

export function getAddressUnblacklistedDecoder(): FixedSizeDecoder<AddressUnblacklisted> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["wallet", getAddressDecoder()],
    ["authority", getAddressDecoder()],
  ]);
}

export function getAddressUnblacklistedCodec(): FixedSizeCodec<
  AddressUnblacklistedArgs,
  AddressUnblacklisted
> {
  return combineCodec(
    getAddressUnblacklistedEncoder(),
    getAddressUnblacklistedDecoder(),
  );
}
