/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type AddressBlacklisted = {
  mint: Address;
  wallet: Address;
  authority: Address;
  reason: string;
};

export type AddressBlacklistedArgs = AddressBlacklisted;

export function getAddressBlacklistedEncoder(): Encoder<AddressBlacklistedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["wallet", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["reason", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getAddressBlacklistedDecoder(): Decoder<AddressBlacklisted> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["wallet", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["reason", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getAddressBlacklistedCodec(): Codec<
  AddressBlacklistedArgs,
  AddressBlacklisted
> {
  return combineCodec(
    getAddressBlacklistedEncoder(),
    getAddressBlacklistedDecoder(),
  );
}
