/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AuthorityTransferred = {
  mint: Address;
  oldAuthority: Address;
  newAuthority: Address;
};

export type AuthorityTransferredArgs = AuthorityTransferred;

export function getAuthorityTransferredEncoder(): FixedSizeEncoder<AuthorityTransferredArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["oldAuthority", getAddressEncoder()],
    ["newAuthority", getAddressEncoder()],
  ]);
}

export function getAuthorityTransferredDecoder(): FixedSizeDecoder<AuthorityTransferred> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["oldAuthority", getAddressDecoder()],
    ["newAuthority", getAddressDecoder()],
  ]);
}

export function getAuthorityTransferredCodec(): FixedSizeCodec<
  AuthorityTransferredArgs,
  AuthorityTransferred
> {
  return combineCodec(
    getAuthorityTransferredEncoder(),
    getAuthorityTransferredDecoder(),
  );
}
