/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MinterUpdated = {
  mint: Address;
  minter: Address;
  quota: bigint;
  active: boolean;
};

export type MinterUpdatedArgs = {
  mint: Address;
  minter: Address;
  quota: number | bigint;
  active: boolean;
};

export function getMinterUpdatedEncoder(): FixedSizeEncoder<MinterUpdatedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["minter", getAddressEncoder()],
    ["quota", getU64Encoder()],
    ["active", getBooleanEncoder()],
  ]);
}

export function getMinterUpdatedDecoder(): FixedSizeDecoder<MinterUpdated> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["minter", getAddressDecoder()],
    ["quota", getU64Decoder()],
    ["active", getBooleanDecoder()],
  ]);
}

export function getMinterUpdatedCodec(): FixedSizeCodec<
  MinterUpdatedArgs,
  MinterUpdated
> {
  return combineCodec(getMinterUpdatedEncoder(), getMinterUpdatedDecoder());
}
