/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PauseChanged = {
  mint: Address;
  paused: boolean;
  authority: Address;
};

export type PauseChangedArgs = PauseChanged;

export function getPauseChangedEncoder(): FixedSizeEncoder<PauseChangedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["paused", getBooleanEncoder()],
    ["authority", getAddressEncoder()],
  ]);
}

export function getPauseChangedDecoder(): FixedSizeDecoder<PauseChanged> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["paused", getBooleanDecoder()],
    ["authority", getAddressDecoder()],
  ]);
}

export function getPauseChangedCodec(): FixedSizeCodec<
  PauseChangedArgs,
  PauseChanged
> {
  return combineCodec(getPauseChangedEncoder(), getPauseChangedDecoder());
}
