/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RolesUpdated = { mint: Address; authority: Address };

export type RolesUpdatedArgs = RolesUpdated;

export function getRolesUpdatedEncoder(): FixedSizeEncoder<RolesUpdatedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["authority", getAddressEncoder()],
  ]);
}

export function getRolesUpdatedDecoder(): FixedSizeDecoder<RolesUpdated> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["authority", getAddressDecoder()],
  ]);
}

export function getRolesUpdatedCodec(): FixedSizeCodec<
  RolesUpdatedArgs,
  RolesUpdated
> {
  return combineCodec(getRolesUpdatedEncoder(), getRolesUpdatedDecoder());
}
