/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type StablecoinInitialized = {
  mint: Address;
  authority: Address;
  preset: string;
};

export type StablecoinInitializedArgs = StablecoinInitialized;

export function getStablecoinInitializedEncoder(): Encoder<StablecoinInitializedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["preset", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getStablecoinInitializedDecoder(): Decoder<StablecoinInitialized> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["preset", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getStablecoinInitializedCodec(): Codec<
  StablecoinInitializedArgs,
  StablecoinInitialized
> {
  return combineCodec(
    getStablecoinInitializedEncoder(),
    getStablecoinInitializedDecoder(),
  );
}
