/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokensMinted = {
  mint: Address;
  to: Address;
  authority: Address;
  amount: bigint;
};

export type TokensMintedArgs = {
  mint: Address;
  to: Address;
  authority: Address;
  amount: number | bigint;
};

export function getTokensMintedEncoder(): FixedSizeEncoder<TokensMintedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["to", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getTokensMintedDecoder(): FixedSizeDecoder<TokensMinted> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["to", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getTokensMintedCodec(): FixedSizeCodec<
  TokensMintedArgs,
  TokensMinted
> {
  return combineCodec(getTokensMintedEncoder(), getTokensMintedDecoder());
}
