/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokensBurned = {
  mint: Address;
  from: Address;
  authority: Address;
  amount: bigint;
};

export type TokensBurnedArgs = {
  mint: Address;
  from: Address;
  authority: Address;
  amount: number | bigint;
};

export function getTokensBurnedEncoder(): FixedSizeEncoder<TokensBurnedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["from", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getTokensBurnedDecoder(): FixedSizeDecoder<TokensBurned> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["from", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getTokensBurnedCodec(): FixedSizeCodec<
  TokensBurnedArgs,
  TokensBurned
> {
  return combineCodec(getTokensBurnedEncoder(), getTokensBurnedDecoder());
}
