/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokensSeized = {
  mint: Address;
  from: Address;
  to: Address;
  authority: Address;
  amount: bigint;
};

export type TokensSeizedArgs = {
  mint: Address;
  from: Address;
  to: Address;
  authority: Address;
  amount: number | bigint;
};

export function getTokensSeizedEncoder(): FixedSizeEncoder<TokensSeizedArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["from", getAddressEncoder()],
    ["to", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getTokensSeizedDecoder(): FixedSizeDecoder<TokensSeized> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["from", getAddressDecoder()],
    ["to", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getTokensSeizedCodec(): FixedSizeCodec<
  TokensSeizedArgs,
  TokensSeized
> {
  return combineCodec(getTokensSeizedEncoder(), getTokensSeizedDecoder());
}
