//! This code was AUTOGENERATED using the Codama library.

pub mod account_frozen;
pub mod account_thawed;
pub mod address_blacklisted;
pub mod address_unblacklisted;
pub mod authority_transferred;
pub mod minter_updated;
pub mod pause_changed;
pub mod roles_updated;
pub mod stablecoin_initialized;
pub mod tokens_burned;
pub mod tokens_minted;
pub mod tokens_seized;

