//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: stablecoin
// ----------------------------------------------------------------------------
pub mod stablecoin {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for stablecoin
    pub fn program_id() -> Pubkey {
        pubkey!("2MKyZ3ugkGyfConZAsqm3hwRoY6c2k7zwZaX1XCSHsJH")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub wallet: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub wallet: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            wallet: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                wallet,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(reason: String) -> Self {
            Self { reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.wallet = AccountMeta::new_readonly(accounts.wallet, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.wallet.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Burn
    // ....................................................................

    /// Main instruction struct for Burn
    pub struct BurnInstruction {
        pub accounts: BurnInstructionAccountMetas,
        pub data: BurnInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Burn instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Burn instruction
    #[derive(Debug, Clone)]
    pub struct BurnInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub token_program: Pubkey,
    }

    impl BurnInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                mint,

                from,

                token_program,
            }
        }
    }

    /// Instruction data for Burn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnInstructionData {
        pub amount: u64,
    }

    impl BurnInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnInstruction
    impl BurnInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 110u8, 29u8, 56u8, 107u8, 219u8, 42u8, 93u8]
        }

        pub fn data(data: BurnInstructionData) -> Self {
            Self {
                accounts: BurnInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub mint: AccountMeta,

        pub account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub mint: Pubkey,

        pub account: Pubkey,

        pub token_program: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            mint: Pubkey,

            account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                mint,

                account,

                token_program,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.account = AccountMeta::new(accounts.account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub transfer_hook_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub transfer_hook_program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            extra_account_meta_list: Pubkey,

            transfer_hook_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                mint,

                config,

                role_config,

                extra_account_meta_list,

                transfer_hook_program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub params: InitializeParams,
    }

    impl InitializeInstructionData {
        pub fn new(params: InitializeParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new(accounts.role_config, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.transfer_hook_program =
                AccountMeta::new_readonly(accounts.transfer_hook_program, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.transfer_hook_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Mint
    // ....................................................................

    /// Main instruction struct for Mint
    pub struct MintInstruction {
        pub accounts: MintInstructionAccountMetas,
        pub data: MintInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Mint instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub minter_quota: AccountMeta,

        pub mint: AccountMeta,

        pub to: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Mint instruction
    #[derive(Debug, Clone)]
    pub struct MintInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub minter_quota: Pubkey,

        pub mint: Pubkey,

        pub to: Pubkey,

        pub token_program: Pubkey,
    }

    impl MintInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            minter_quota: Pubkey,

            mint: Pubkey,

            to: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                minter_quota,

                mint,

                to,

                token_program,
            }
        }
    }

    /// Instruction data for Mint
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintInstructionData {
        pub amount: u64,
    }

    impl MintInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintInstruction
    impl MintInstruction {
        fn discriminator() -> [u8; 8] {
            [51u8, 57u8, 225u8, 47u8, 182u8, 146u8, 137u8, 166u8]
        }

        pub fn data(data: MintInstructionData) -> Self {
            Self {
                accounts: MintInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.minter_quota = AccountMeta::new(accounts.minter_quota, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_quota.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, role_config: Pubkey) -> Self {
            Self {
                authority,

                config,

                role_config,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {}

    impl RemoveFromBlacklistInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub stablecoin_program: AccountMeta,

        pub transfer_hook_program: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub destination_blacklist: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub blacklist_entry: Pubkey,

        pub transfer_hook_program: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub destination_blacklist: Pubkey,

        pub token_program: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            to: Pubkey,

            blacklist_entry: Pubkey,

            transfer_hook_program: Pubkey,

            extra_account_meta_list: Pubkey,

            destination_blacklist: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                mint,

                from,

                to,

                blacklist_entry,

                transfer_hook_program,

                extra_account_meta_list,

                destination_blacklist,

                token_program,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.blacklist_entry =
                AccountMeta::new_readonly(accounts.blacklist_entry, false);

            self.accounts.stablecoin_program = AccountMeta::new_readonly(
                pubkey!("2MKyZ3ugkGyfConZAsqm3hwRoY6c2k7zwZaX1XCSHsJH"),
                false,
            );

            self.accounts.transfer_hook_program =
                AccountMeta::new_readonly(accounts.transfer_hook_program, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.destination_blacklist =
                AccountMeta::new_readonly(accounts.destination_blacklist, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.stablecoin_program.clone());

            metas.push(self.accounts.transfer_hook_program.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.destination_blacklist.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub mint: AccountMeta,

        pub account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub mint: Pubkey,

        pub account: Pubkey,

        pub token_program: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            mint: Pubkey,

            account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                mint,

                account,

                token_program,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.account = AccountMeta::new(accounts.account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAuthority
    // ....................................................................

    /// Main instruction struct for TransferAuthority
    pub struct TransferAuthorityInstruction {
        pub accounts: TransferAuthorityInstructionAccountMetas,
        pub data: TransferAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAuthorityInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,
    }

    /// Account pubkeys for TransferAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferAuthorityInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,
    }

    impl TransferAuthorityInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, role_config: Pubkey) -> Self {
            Self {
                authority,

                config,

                role_config,
            }
        }
    }

    /// Instruction data for TransferAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAuthorityInstructionData {
        pub new_authority: Pubkey,
    }

    impl TransferAuthorityInstructionData {
        pub fn new(new_authority: Pubkey) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for TransferAuthorityInstruction
    impl TransferAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 169u8, 76u8, 72u8, 229u8, 180u8, 55u8, 161u8]
        }

        pub fn data(data: TransferAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAuthorityInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new(accounts.role_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, role_config: Pubkey) -> Self {
            Self {
                authority,

                config,

                role_config,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,

        pub mint: AccountMeta,

        pub minter: AccountMeta,

        pub minter_quota: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,

        pub mint: Pubkey,

        pub minter: Pubkey,

        pub minter_quota: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            role_config: Pubkey,

            mint: Pubkey,

            minter: Pubkey,

            minter_quota: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                role_config,

                mint,

                minter,

                minter_quota,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub params: UpdateMinterParams,
    }

    impl UpdateMinterInstructionData {
        pub fn new(params: UpdateMinterParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new_readonly(accounts.role_config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, false);

            self.accounts.minter_quota = AccountMeta::new(accounts.minter_quota, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.minter_quota.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_config: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_config: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, role_config: Pubkey) -> Self {
            Self {
                authority,

                config,

                role_config,
            }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub params: UpdateRolesParams,
    }

    impl UpdateRolesInstructionData {
        pub fn new(params: UpdateRolesParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_config = AccountMeta::new(accounts.role_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: transfer_hook
// ----------------------------------------------------------------------------
pub mod transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("6mjTtZjRFK8FWA24f2KNEfMVcAvpYLWcpMzLvKiVXyd2")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(payer: Pubkey, extra_account_meta_list: Pubkey, mint: Pubkey) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {}

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [43u8, 34u8, 13u8, 49u8, 167u8, 88u8, 235u8, 235u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source: AccountMeta,

        pub mint: AccountMeta,

        pub destination: AccountMeta,

        pub authority: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub stablecoin_program: AccountMeta,

        pub config: AccountMeta,

        pub source_blacklist: AccountMeta,

        pub destination_blacklist: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source: Pubkey,

        pub mint: Pubkey,

        pub destination: Pubkey,

        pub authority: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub stablecoin_program: Pubkey,

        pub config: Pubkey,

        pub source_blacklist: Pubkey,

        pub destination_blacklist: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source: Pubkey,

            mint: Pubkey,

            destination: Pubkey,

            authority: Pubkey,

            extra_account_meta_list: Pubkey,

            stablecoin_program: Pubkey,

            config: Pubkey,

            source_blacklist: Pubkey,

            destination_blacklist: Pubkey,
        ) -> Self {
            Self {
                source,

                mint,

                destination,

                authority,

                extra_account_meta_list,

                stablecoin_program,

                config,

                source_blacklist,

                destination_blacklist,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub _amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(_amount: u64) -> Self {
            Self { _amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [105u8, 37u8, 101u8, 197u8, 75u8, 251u8, 102u8, 26u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source = AccountMeta::new_readonly(accounts.source, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination = AccountMeta::new_readonly(accounts.destination, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.stablecoin_program =
                AccountMeta::new_readonly(accounts.stablecoin_program, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.source_blacklist =
                AccountMeta::new_readonly(accounts.source_blacklist, false);

            self.accounts.destination_blacklist =
                AccountMeta::new_readonly(accounts.destination_blacklist, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.stablecoin_program.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.source_blacklist.clone());

            metas.push(self.accounts.destination_blacklist.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AccountFrozen
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountFrozen {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub authority: Pubkey,
}

impl AccountFrozen {
    pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey) -> Self {
        Self {
            mint,

            account,

            authority,
        }
    }
}

/// Custom struct: AccountThawed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountThawed {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub authority: Pubkey,
}

impl AccountThawed {
    pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey) -> Self {
        Self {
            mint,

            account,

            authority,
        }
    }
}

/// Custom struct: AddressBlacklisted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddressBlacklisted {
    pub mint: Pubkey,

    pub wallet: Pubkey,

    pub authority: Pubkey,

    pub reason: String,
}

impl AddressBlacklisted {
    pub fn new(mint: Pubkey, wallet: Pubkey, authority: Pubkey, reason: String) -> Self {
        Self {
            mint,

            wallet,

            authority,

            reason,
        }
    }
}

/// Custom struct: AddressUnblacklisted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddressUnblacklisted {
    pub mint: Pubkey,

    pub wallet: Pubkey,

    pub authority: Pubkey,
}

impl AddressUnblacklisted {
    pub fn new(mint: Pubkey, wallet: Pubkey, authority: Pubkey) -> Self {
        Self {
            mint,

            wallet,

            authority,
        }
    }
}

/// Custom struct: AuthorityTransferred
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityTransferred {
    pub mint: Pubkey,

    pub old_authority: Pubkey,

    pub new_authority: Pubkey,
}

impl AuthorityTransferred {
    pub fn new(mint: Pubkey, old_authority: Pubkey, new_authority: Pubkey) -> Self {
        Self {
            mint,

            old_authority,

            new_authority,
        }
    }
}

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub mint: Pubkey,

    pub wallet: Pubkey,

    pub reason: String,

    pub blacklisted_by: Pubkey,

    pub blacklisted_at: i64,

    pub bump: u8,
}

impl BlacklistEntry {
    pub fn new(
        mint: Pubkey,

        wallet: Pubkey,

        reason: String,

        blacklisted_by: Pubkey,

        blacklisted_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            wallet,

            reason,

            blacklisted_by,

            blacklisted_at,

            bump,
        }
    }
}

/// Custom struct: InitializeParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeParams {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,
}

impl InitializeParams {
    pub fn new(
        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,
    ) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,
        }
    }
}

/// Custom struct: MinterQuota
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterQuota {
    pub mint: Pubkey,

    pub minter: Pubkey,

    pub quota: u64,

    pub minted: u64,

    pub active: bool,

    pub created_at: i64,

    pub bump: u8,
}

impl MinterQuota {
    pub fn new(
        mint: Pubkey,

        minter: Pubkey,

        quota: u64,

        minted: u64,

        active: bool,

        created_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            minter,

            quota,

            minted,

            active,

            created_at,

            bump,
        }
    }
}

/// Custom struct: MinterUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterUpdated {
    pub mint: Pubkey,

    pub minter: Pubkey,

    pub quota: u64,

    pub active: bool,
}

impl MinterUpdated {
    pub fn new(mint: Pubkey, minter: Pubkey, quota: u64, active: bool) -> Self {
        Self {
            mint,

            minter,

            quota,

            active,
        }
    }
}

/// Custom struct: PauseChanged
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PauseChanged {
    pub mint: Pubkey,

    pub paused: bool,

    pub authority: Pubkey,
}

impl PauseChanged {
    pub fn new(mint: Pubkey, paused: bool, authority: Pubkey) -> Self {
        Self {
            mint,

            paused,

            authority,
        }
    }
}

/// Custom struct: RoleConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleConfig {
    pub mint: Pubkey,

    pub master_authority: Pubkey,

    pub pauser: Pubkey,

    pub burner: Pubkey,

    pub blacklister: Pubkey,

    pub seizer: Pubkey,

    pub bump: u8,
}

impl RoleConfig {
    pub fn new(
        mint: Pubkey,

        master_authority: Pubkey,

        pauser: Pubkey,

        burner: Pubkey,

        blacklister: Pubkey,

        seizer: Pubkey,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            master_authority,

            pauser,

            burner,

            blacklister,

            seizer,

            bump,
        }
    }
}

/// Custom struct: RolesUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RolesUpdated {
    pub mint: Pubkey,

    pub authority: Pubkey,
}

impl RolesUpdated {
    pub fn new(mint: Pubkey, authority: Pubkey) -> Self {
        Self { mint, authority }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub mint: Pubkey,

    pub authority: Pubkey,

    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub paused: bool,

    pub total_minted: u64,

    pub total_burned: u64,

    pub created_at: i64,

    pub last_changed_by: Pubkey,

    pub last_changed_at: i64,

    pub bump: u8,
}

impl StablecoinConfig {
    pub fn new(
        mint: Pubkey,

        authority: Pubkey,

        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        paused: bool,

        total_minted: u64,

        total_burned: u64,

        created_at: i64,

        last_changed_by: Pubkey,

        last_changed_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            authority,

            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            paused,

            total_minted,

            total_burned,

            created_at,

            last_changed_by,

            last_changed_at,

            bump,
        }
    }
}

/// Custom struct: StablecoinInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinInitialized {
    pub mint: Pubkey,

    pub authority: Pubkey,

    pub preset: String,
}

impl StablecoinInitialized {
    pub fn new(mint: Pubkey, authority: Pubkey, preset: String) -> Self {
        Self {
            mint,

            authority,

            preset,
        }
    }
}

/// Custom struct: TokensBurned
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensBurned {
    pub mint: Pubkey,

    pub from: Pubkey,

    pub authority: Pubkey,

    pub amount: u64,
}

impl TokensBurned {
    pub fn new(mint: Pubkey, from: Pubkey, authority: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            from,

            authority,

            amount,
        }
    }
}

/// Custom struct: TokensMinted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensMinted {
    pub mint: Pubkey,

    pub to: Pubkey,

    pub authority: Pubkey,

    pub amount: u64,
}

impl TokensMinted {
    pub fn new(mint: Pubkey, to: Pubkey, authority: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            to,

            authority,

            amount,
        }
    }
}

/// Custom struct: TokensSeized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensSeized {
    pub mint: Pubkey,

    pub from: Pubkey,

    pub to: Pubkey,

    pub authority: Pubkey,

    pub amount: u64,
}

impl TokensSeized {
    pub fn new(mint: Pubkey, from: Pubkey, to: Pubkey, authority: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            from,

            to,

            authority,

            amount,
        }
    }
}

/// Custom struct: UpdateMinterParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateMinterParams {
    pub minter: Pubkey,

    pub quota: u64,

    pub active: bool,
}

impl UpdateMinterParams {
    pub fn new(minter: Pubkey, quota: u64, active: bool) -> Self {
        Self {
            minter,

            quota,

            active,
        }
    }
}

/// Custom struct: UpdateRolesParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateRolesParams {
    pub pauser: Option<Pubkey>,

    pub burner: Option<Pubkey>,

    pub blacklister: Option<Pubkey>,

    pub seizer: Option<Pubkey>,
}

impl UpdateRolesParams {
    pub fn new(
        pauser: Option<Pubkey>,

        burner: Option<Pubkey>,

        blacklister: Option<Pubkey>,

        seizer: Option<Pubkey>,
    ) -> Self {
        Self {
            pauser,

            burner,

            blacklister,

            seizer,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
