/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";

/** InvalidStablecoinProgram: Stablecoin program account is invalid */
export const TRANSFER_HOOK_ERROR__INVALID_STABLECOIN_PROGRAM = 0x1770; // 6000
/** InvalidConfigAccount: Stablecoin config account is invalid */
export const TRANSFER_HOOK_ERROR__INVALID_CONFIG_ACCOUNT = 0x1771; // 6001
/** InvalidBlacklistAccount: Blacklist PDA account is invalid */
export const TRANSFER_HOOK_ERROR__INVALID_BLACKLIST_ACCOUNT = 0x1772; // 6002
/** SourceBlacklisted: Source address is blacklisted */
export const TRANSFER_HOOK_ERROR__SOURCE_BLACKLISTED = 0x1773; // 6003
/** DestinationBlacklisted: Destination address is blacklisted */
export const TRANSFER_HOOK_ERROR__DESTINATION_BLACKLISTED = 0x1774; // 6004
/** InvalidExtraAccountMetaList: Extra account meta list is invalid */
export const TRANSFER_HOOK_ERROR__INVALID_EXTRA_ACCOUNT_META_LIST = 0x1775; // 6005
/** InvalidInstruction: Unsupported transfer hook instruction */
export const TRANSFER_HOOK_ERROR__INVALID_INSTRUCTION = 0x1776; // 6006

export type TransferHookError =
  | typeof TRANSFER_HOOK_ERROR__DESTINATION_BLACKLISTED
  | typeof TRANSFER_HOOK_ERROR__INVALID_BLACKLIST_ACCOUNT
  | typeof TRANSFER_HOOK_ERROR__INVALID_CONFIG_ACCOUNT
  | typeof TRANSFER_HOOK_ERROR__INVALID_EXTRA_ACCOUNT_META_LIST
  | typeof TRANSFER_HOOK_ERROR__INVALID_INSTRUCTION
  | typeof TRANSFER_HOOK_ERROR__INVALID_STABLECOIN_PROGRAM
  | typeof TRANSFER_HOOK_ERROR__SOURCE_BLACKLISTED;

let transferHookErrorMessages: Record<TransferHookError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  transferHookErrorMessages = {
    [TRANSFER_HOOK_ERROR__DESTINATION_BLACKLISTED]: `Destination address is blacklisted`,
    [TRANSFER_HOOK_ERROR__INVALID_BLACKLIST_ACCOUNT]: `Blacklist PDA account is invalid`,
    [TRANSFER_HOOK_ERROR__INVALID_CONFIG_ACCOUNT]: `Stablecoin config account is invalid`,
    [TRANSFER_HOOK_ERROR__INVALID_EXTRA_ACCOUNT_META_LIST]: `Extra account meta list is invalid`,
    [TRANSFER_HOOK_ERROR__INVALID_INSTRUCTION]: `Unsupported transfer hook instruction`,
    [TRANSFER_HOOK_ERROR__INVALID_STABLECOIN_PROGRAM]: `Stablecoin program account is invalid`,
    [TRANSFER_HOOK_ERROR__SOURCE_BLACKLISTED]: `Source address is blacklisted`,
  };
}

export function getTransferHookErrorMessage(code: TransferHookError): string {
  if (process.env.NODE_ENV !== "production") {
    return (transferHookErrorMessages as Record<TransferHookError, string>)[
      code
    ];
  }

  return "Error message not available in production bundles.";
}

export function isTransferHookError<
  TProgramErrorCode extends TransferHookError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    TRANSFER_HOOK_PROGRAM_ADDRESS,
    code,
  );
}
