//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::StablecoinDecoder;



pub mod blacklist_entry;
pub mod minter_quota;
pub mod role_config;
pub mod stablecoin_config;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum StablecoinAccount {
    BlacklistEntry(Box<blacklist_entry::BlacklistEntry>),
    MinterQuota(Box<minter_quota::MinterQuota>),
    RoleConfig(Box<role_config::RoleConfig>),
    StablecoinConfig(Box<stablecoin_config::StablecoinConfig>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for StablecoinDecoder {
    type AccountType = StablecoinAccount;
    
    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }
        
        let data = account.data.as_slice();
        
        {
            if let Some(decoded) = blacklist_entry::BlacklistEntry::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: StablecoinAccount::BlacklistEntry(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = minter_quota::MinterQuota::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: StablecoinAccount::MinterQuota(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = role_config::RoleConfig::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: StablecoinAccount::RoleConfig(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = stablecoin_config::StablecoinConfig::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: StablecoinAccount::StablecoinConfig(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        
        None
    }
}

