/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const ADD_TO_BLACKLIST_DISCRIMINATOR = new Uint8Array([
  90, 115, 98, 231, 173, 119, 117, 176,
]);

export function getAddToBlacklistDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ADD_TO_BLACKLIST_DISCRIMINATOR,
  );
}

export type AddToBlacklistInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TAccountWallet extends string | AccountMeta<string> = string,
  TAccountBlacklistEntry extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? ReadonlyAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      TAccountWallet extends string
        ? ReadonlyAccount<TAccountWallet>
        : TAccountWallet,
      TAccountBlacklistEntry extends string
        ? WritableAccount<TAccountBlacklistEntry>
        : TAccountBlacklistEntry,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AddToBlacklistInstructionData = {
  discriminator: ReadonlyUint8Array;
  reason: string;
};

export type AddToBlacklistInstructionDataArgs = { reason: string };

export function getAddToBlacklistInstructionDataEncoder(): Encoder<AddToBlacklistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["reason", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: ADD_TO_BLACKLIST_DISCRIMINATOR }),
  );
}

export function getAddToBlacklistInstructionDataDecoder(): Decoder<AddToBlacklistInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["reason", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getAddToBlacklistInstructionDataCodec(): Codec<
  AddToBlacklistInstructionDataArgs,
  AddToBlacklistInstructionData
> {
  return combineCodec(
    getAddToBlacklistInstructionDataEncoder(),
    getAddToBlacklistInstructionDataDecoder(),
  );
}

export type AddToBlacklistInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
  TAccountWallet extends string = string,
  TAccountBlacklistEntry extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  wallet: Address<TAccountWallet>;
  blacklistEntry: Address<TAccountBlacklistEntry>;
  systemProgram?: Address<TAccountSystemProgram>;
  reason: AddToBlacklistInstructionDataArgs["reason"];
};

export function getAddToBlacklistInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TAccountWallet extends string,
  TAccountBlacklistEntry extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: AddToBlacklistInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountWallet,
    TAccountBlacklistEntry,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AddToBlacklistInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig,
  TAccountWallet,
  TAccountBlacklistEntry,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
    wallet: { value: input.wallet ?? null, isWritable: false },
    blacklistEntry: { value: input.blacklistEntry ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
      getAccountMeta("wallet", accounts.wallet),
      getAccountMeta("blacklistEntry", accounts.blacklistEntry),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAddToBlacklistInstructionDataEncoder().encode(
      args as AddToBlacklistInstructionDataArgs,
    ),
    programAddress,
  } as AddToBlacklistInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountWallet,
    TAccountBlacklistEntry,
    TAccountSystemProgram
  >);
}

export type ParsedAddToBlacklistInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
    wallet: TAccountMetas[3];
    blacklistEntry: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: AddToBlacklistInstructionData;
};

export function parseAddToBlacklistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddToBlacklistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
      wallet: getNextAccount(),
      blacklistEntry: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAddToBlacklistInstructionDataDecoder().decode(instruction.data),
  };
}
