/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const MINT_DISCRIMINATOR = new Uint8Array([
  51, 57, 225, 47, 182, 146, 137, 166,
]);

export function getMintDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MINT_DISCRIMINATOR);
}

export type MintInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMinterQuota extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTo extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMinterQuota extends string
        ? WritableAccount<TAccountMinterQuota>
        : TAccountMinterQuota,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type MintInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type MintInstructionDataArgs = { amount: number | bigint };

export function getMintInstructionDataEncoder(): FixedSizeEncoder<MintInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINT_DISCRIMINATOR }),
  );
}

export function getMintInstructionDataDecoder(): FixedSizeDecoder<MintInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getMintInstructionDataCodec(): FixedSizeCodec<
  MintInstructionDataArgs,
  MintInstructionData
> {
  return combineCodec(
    getMintInstructionDataEncoder(),
    getMintInstructionDataDecoder(),
  );
}

export type MintAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountMinterQuota extends string = string,
  TAccountMint extends string = string,
  TAccountTo extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config?: Address<TAccountConfig>;
  minterQuota?: Address<TAccountMinterQuota>;
  mint: Address<TAccountMint>;
  to: Address<TAccountTo>;
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: MintInstructionDataArgs["amount"];
};

export async function getMintInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountMinterQuota extends string,
  TAccountMint extends string,
  TAccountTo extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: MintAsyncInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountMinterQuota,
    TAccountMint,
    TAccountTo,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MintInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountMinterQuota,
    TAccountMint,
    TAccountTo,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    minterQuota: { value: input.minterQuota ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.minterQuota.value) {
    accounts.minterQuota.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 105, 110, 116, 101, 114]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "authority",
            accounts.authority.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("minterQuota", accounts.minterQuota),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("to", accounts.to),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getMintInstructionDataEncoder().encode(
      args as MintInstructionDataArgs,
    ),
    programAddress,
  } as MintInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountMinterQuota,
    TAccountMint,
    TAccountTo,
    TAccountTokenProgram
  >);
}

export type MintInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountMinterQuota extends string = string,
  TAccountMint extends string = string,
  TAccountTo extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  minterQuota: Address<TAccountMinterQuota>;
  mint: Address<TAccountMint>;
  to: Address<TAccountTo>;
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: MintInstructionDataArgs["amount"];
};

export function getMintInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountMinterQuota extends string,
  TAccountMint extends string,
  TAccountTo extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: MintInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountMinterQuota,
    TAccountMint,
    TAccountTo,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): MintInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountMinterQuota,
  TAccountMint,
  TAccountTo,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    minterQuota: { value: input.minterQuota ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("minterQuota", accounts.minterQuota),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("to", accounts.to),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getMintInstructionDataEncoder().encode(
      args as MintInstructionDataArgs,
    ),
    programAddress,
  } as MintInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountMinterQuota,
    TAccountMint,
    TAccountTo,
    TAccountTokenProgram
  >);
}

export type ParsedMintInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    minterQuota: TAccountMetas[2];
    mint: TAccountMetas[3];
    to: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
  };
  data: MintInstructionData;
};

export function parseMintInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMintInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      minterQuota: getNextAccount(),
      mint: getNextAccount(),
      to: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getMintInstructionDataDecoder().decode(instruction.data),
  };
}
