/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const PAUSE_DISCRIMINATOR = new Uint8Array([
  211, 22, 221, 251, 74, 121, 193, 47,
]);

export function getPauseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PAUSE_DISCRIMINATOR);
}

export type PauseInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? ReadonlyAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      ...TRemainingAccounts,
    ]
  >;

export type PauseInstructionData = { discriminator: ReadonlyUint8Array };

export type PauseInstructionDataArgs = {};

export function getPauseInstructionDataEncoder(): FixedSizeEncoder<PauseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: PAUSE_DISCRIMINATOR }),
  );
}

export function getPauseInstructionDataDecoder(): FixedSizeDecoder<PauseInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getPauseInstructionDataCodec(): FixedSizeCodec<
  PauseInstructionDataArgs,
  PauseInstructionData
> {
  return combineCodec(
    getPauseInstructionDataEncoder(),
    getPauseInstructionDataDecoder(),
  );
}

export type PauseInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
};

export function getPauseInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: PauseInput<TAccountAuthority, TAccountConfig, TAccountRoleConfig>,
  config?: { programAddress?: TProgramAddress },
): PauseInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
    ],
    data: getPauseInstructionDataEncoder().encode({}),
    programAddress,
  } as PauseInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig
  >);
}

export type ParsedPauseInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
  };
  data: PauseInstructionData;
};

export function parsePauseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPauseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
    },
    data: getPauseInstructionDataDecoder().decode(instruction.data),
  };
}
