/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const REMOVE_FROM_BLACKLIST_DISCRIMINATOR = new Uint8Array([
  47, 105, 20, 10, 165, 168, 203, 219,
]);

export function getRemoveFromBlacklistDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REMOVE_FROM_BLACKLIST_DISCRIMINATOR,
  );
}

export type RemoveFromBlacklistInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TAccountBlacklistEntry extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? ReadonlyAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      TAccountBlacklistEntry extends string
        ? WritableAccount<TAccountBlacklistEntry>
        : TAccountBlacklistEntry,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveFromBlacklistInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type RemoveFromBlacklistInstructionDataArgs = {};

export function getRemoveFromBlacklistInstructionDataEncoder(): FixedSizeEncoder<RemoveFromBlacklistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: REMOVE_FROM_BLACKLIST_DISCRIMINATOR,
    }),
  );
}

export function getRemoveFromBlacklistInstructionDataDecoder(): FixedSizeDecoder<RemoveFromBlacklistInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRemoveFromBlacklistInstructionDataCodec(): FixedSizeCodec<
  RemoveFromBlacklistInstructionDataArgs,
  RemoveFromBlacklistInstructionData
> {
  return combineCodec(
    getRemoveFromBlacklistInstructionDataEncoder(),
    getRemoveFromBlacklistInstructionDataDecoder(),
  );
}

export type RemoveFromBlacklistAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
  TAccountBlacklistEntry extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  blacklistEntry: Address<TAccountBlacklistEntry>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
};

export async function getRemoveFromBlacklistInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TAccountBlacklistEntry extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: RemoveFromBlacklistAsyncInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountBlacklistEntry,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RemoveFromBlacklistInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountBlacklistEntry,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
    blacklistEntry: { value: input.blacklistEntry ?? null, isWritable: true },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
      getAccountMeta("blacklistEntry", accounts.blacklistEntry),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
    ],
    data: getRemoveFromBlacklistInstructionDataEncoder().encode({}),
    programAddress,
  } as RemoveFromBlacklistInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountBlacklistEntry,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type RemoveFromBlacklistInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
  TAccountBlacklistEntry extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  blacklistEntry: Address<TAccountBlacklistEntry>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
};

export function getRemoveFromBlacklistInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TAccountBlacklistEntry extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: RemoveFromBlacklistInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountBlacklistEntry,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RemoveFromBlacklistInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig,
  TAccountBlacklistEntry,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
    blacklistEntry: { value: input.blacklistEntry ?? null, isWritable: true },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
      getAccountMeta("blacklistEntry", accounts.blacklistEntry),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
    ],
    data: getRemoveFromBlacklistInstructionDataEncoder().encode({}),
    programAddress,
  } as RemoveFromBlacklistInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountBlacklistEntry,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedRemoveFromBlacklistInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
    blacklistEntry: TAccountMetas[3];
    eventAuthority: TAccountMetas[4];
    program: TAccountMetas[5];
  };
  data: RemoveFromBlacklistInstructionData;
};

export function parseRemoveFromBlacklistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRemoveFromBlacklistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
      blacklistEntry: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getRemoveFromBlacklistInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
