/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const TRANSFER_AUTHORITY_DISCRIMINATOR = new Uint8Array([
  48, 169, 76, 72, 229, 180, 55, 161,
]);

export function getTransferAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_AUTHORITY_DISCRIMINATOR,
  );
}

export type TransferAuthorityInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? WritableAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      ...TRemainingAccounts,
    ]
  >;

export type TransferAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
  newAuthority: Address;
};

export type TransferAuthorityInstructionDataArgs = { newAuthority: Address };

export function getTransferAuthorityInstructionDataEncoder(): FixedSizeEncoder<TransferAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["newAuthority", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_AUTHORITY_DISCRIMINATOR }),
  );
}

export function getTransferAuthorityInstructionDataDecoder(): FixedSizeDecoder<TransferAuthorityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["newAuthority", getAddressDecoder()],
  ]);
}

export function getTransferAuthorityInstructionDataCodec(): FixedSizeCodec<
  TransferAuthorityInstructionDataArgs,
  TransferAuthorityInstructionData
> {
  return combineCodec(
    getTransferAuthorityInstructionDataEncoder(),
    getTransferAuthorityInstructionDataDecoder(),
  );
}

export type TransferAuthorityInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  newAuthority: TransferAuthorityInstructionDataArgs["newAuthority"];
};

export function getTransferAuthorityInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: TransferAuthorityInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig
  >,
  config?: { programAddress?: TProgramAddress },
): TransferAuthorityInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    roleConfig: { value: input.roleConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
    ],
    data: getTransferAuthorityInstructionDataEncoder().encode(
      args as TransferAuthorityInstructionDataArgs,
    ),
    programAddress,
  } as TransferAuthorityInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig
  >);
}

export type ParsedTransferAuthorityInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
  };
  data: TransferAuthorityInstructionData;
};

export function parseTransferAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
    },
    data: getTransferAuthorityInstructionDataDecoder().decode(instruction.data),
  };
}
