/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const UPDATE_ROLES_DISCRIMINATOR = new Uint8Array([
  220, 152, 205, 233, 177, 123, 219, 125,
]);

export function getUpdateRolesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ROLES_DISCRIMINATOR,
  );
}

export type UpdateRolesInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? WritableAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateRolesInstructionData = {
  discriminator: ReadonlyUint8Array;
  pauser: Option<Address>;
  burner: Option<Address>;
  blacklister: Option<Address>;
  seizer: Option<Address>;
};

export type UpdateRolesInstructionDataArgs = {
  pauser: OptionOrNullable<Address>;
  burner: OptionOrNullable<Address>;
  blacklister: OptionOrNullable<Address>;
  seizer: OptionOrNullable<Address>;
};

export function getUpdateRolesInstructionDataEncoder(): Encoder<UpdateRolesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["pauser", getOptionEncoder(getAddressEncoder())],
      ["burner", getOptionEncoder(getAddressEncoder())],
      ["blacklister", getOptionEncoder(getAddressEncoder())],
      ["seizer", getOptionEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_ROLES_DISCRIMINATOR }),
  );
}

export function getUpdateRolesInstructionDataDecoder(): Decoder<UpdateRolesInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["pauser", getOptionDecoder(getAddressDecoder())],
    ["burner", getOptionDecoder(getAddressDecoder())],
    ["blacklister", getOptionDecoder(getAddressDecoder())],
    ["seizer", getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getUpdateRolesInstructionDataCodec(): Codec<
  UpdateRolesInstructionDataArgs,
  UpdateRolesInstructionData
> {
  return combineCodec(
    getUpdateRolesInstructionDataEncoder(),
    getUpdateRolesInstructionDataDecoder(),
  );
}

export type UpdateRolesInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  pauser: UpdateRolesInstructionDataArgs["pauser"];
  burner: UpdateRolesInstructionDataArgs["burner"];
  blacklister: UpdateRolesInstructionDataArgs["blacklister"];
  seizer: UpdateRolesInstructionDataArgs["seizer"];
};

export function getUpdateRolesInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: UpdateRolesInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateRolesInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    roleConfig: { value: input.roleConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
    ],
    data: getUpdateRolesInstructionDataEncoder().encode(
      args as UpdateRolesInstructionDataArgs,
    ),
    programAddress,
  } as UpdateRolesInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig
  >);
}

export type ParsedUpdateRolesInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
  };
  data: UpdateRolesInstructionData;
};

export function parseUpdateRolesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateRolesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
    },
    data: getUpdateRolesInstructionDataDecoder().decode(instruction.data),
  };
}
