/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const BLACKLIST_ENTRY_DISCRIMINATOR = new Uint8Array([
  218, 179, 231, 40, 141, 25, 168, 189,
]);

export function getBlacklistEntryDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BLACKLIST_ENTRY_DISCRIMINATOR,
  );
}

export type BlacklistEntry = {
  discriminator: ReadonlyUint8Array;
  mint: Address;
  wallet: Address;
  reason: string;
  blacklistedBy: Address;
  blacklistedAt: bigint;
  bump: number;
};

export type BlacklistEntryArgs = {
  mint: Address;
  wallet: Address;
  reason: string;
  blacklistedBy: Address;
  blacklistedAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link BlacklistEntryArgs} account data. */
export function getBlacklistEntryEncoder(): Encoder<BlacklistEntryArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mint", getAddressEncoder()],
      ["wallet", getAddressEncoder()],
      ["reason", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["blacklistedBy", getAddressEncoder()],
      ["blacklistedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BLACKLIST_ENTRY_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link BlacklistEntry} account data. */
export function getBlacklistEntryDecoder(): Decoder<BlacklistEntry> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mint", getAddressDecoder()],
    ["wallet", getAddressDecoder()],
    ["reason", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["blacklistedBy", getAddressDecoder()],
    ["blacklistedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link BlacklistEntry} account data. */
export function getBlacklistEntryCodec(): Codec<
  BlacklistEntryArgs,
  BlacklistEntry
> {
  return combineCodec(getBlacklistEntryEncoder(), getBlacklistEntryDecoder());
}

export function decodeBlacklistEntry<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<BlacklistEntry, TAddress>;
export function decodeBlacklistEntry<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<BlacklistEntry, TAddress>;
export function decodeBlacklistEntry<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<BlacklistEntry, TAddress> | MaybeAccount<BlacklistEntry, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBlacklistEntryDecoder(),
  );
}

export async function fetchBlacklistEntry<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<BlacklistEntry, TAddress>> {
  const maybeAccount = await fetchMaybeBlacklistEntry(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBlacklistEntry<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<BlacklistEntry, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBlacklistEntry(maybeAccount);
}

export async function fetchAllBlacklistEntry(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<BlacklistEntry>[]> {
  const maybeAccounts = await fetchAllMaybeBlacklistEntry(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBlacklistEntry(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<BlacklistEntry>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeBlacklistEntry(maybeAccount),
  );
}
