/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const MINTER_QUOTA_DISCRIMINATOR = new Uint8Array([
  42, 21, 27, 217, 49, 82, 230, 89,
]);

export function getMinterQuotaDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MINTER_QUOTA_DISCRIMINATOR,
  );
}

export type MinterQuota = {
  discriminator: ReadonlyUint8Array;
  mint: Address;
  minter: Address;
  quota: bigint;
  minted: bigint;
  active: boolean;
  createdAt: bigint;
  bump: number;
};

export type MinterQuotaArgs = {
  mint: Address;
  minter: Address;
  quota: number | bigint;
  minted: number | bigint;
  active: boolean;
  createdAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link MinterQuotaArgs} account data. */
export function getMinterQuotaEncoder(): FixedSizeEncoder<MinterQuotaArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mint", getAddressEncoder()],
      ["minter", getAddressEncoder()],
      ["quota", getU64Encoder()],
      ["minted", getU64Encoder()],
      ["active", getBooleanEncoder()],
      ["createdAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINTER_QUOTA_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link MinterQuota} account data. */
export function getMinterQuotaDecoder(): FixedSizeDecoder<MinterQuota> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mint", getAddressDecoder()],
    ["minter", getAddressDecoder()],
    ["quota", getU64Decoder()],
    ["minted", getU64Decoder()],
    ["active", getBooleanDecoder()],
    ["createdAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link MinterQuota} account data. */
export function getMinterQuotaCodec(): FixedSizeCodec<
  MinterQuotaArgs,
  MinterQuota
> {
  return combineCodec(getMinterQuotaEncoder(), getMinterQuotaDecoder());
}

export function decodeMinterQuota<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<MinterQuota, TAddress>;
export function decodeMinterQuota<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<MinterQuota, TAddress>;
export function decodeMinterQuota<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<MinterQuota, TAddress> | MaybeAccount<MinterQuota, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMinterQuotaDecoder(),
  );
}

export async function fetchMinterQuota<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<MinterQuota, TAddress>> {
  const maybeAccount = await fetchMaybeMinterQuota(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMinterQuota<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<MinterQuota, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMinterQuota(maybeAccount);
}

export async function fetchAllMinterQuota(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<MinterQuota>[]> {
  const maybeAccounts = await fetchAllMaybeMinterQuota(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMinterQuota(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<MinterQuota>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMinterQuota(maybeAccount));
}

export function getMinterQuotaSize(): number {
  return 98;
}
