/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ROLE_CONFIG_DISCRIMINATOR = new Uint8Array([
  60, 138, 76, 113, 196, 104, 162, 73,
]);

export function getRoleConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ROLE_CONFIG_DISCRIMINATOR);
}

export type RoleConfig = {
  discriminator: ReadonlyUint8Array;
  mint: Address;
  masterAuthority: Address;
  pauser: Address;
  burner: Address;
  blacklister: Address;
  seizer: Address;
  bump: number;
};

export type RoleConfigArgs = {
  mint: Address;
  masterAuthority: Address;
  pauser: Address;
  burner: Address;
  blacklister: Address;
  seizer: Address;
  bump: number;
};

/** Gets the encoder for {@link RoleConfigArgs} account data. */
export function getRoleConfigEncoder(): FixedSizeEncoder<RoleConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mint", getAddressEncoder()],
      ["masterAuthority", getAddressEncoder()],
      ["pauser", getAddressEncoder()],
      ["burner", getAddressEncoder()],
      ["blacklister", getAddressEncoder()],
      ["seizer", getAddressEncoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ROLE_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link RoleConfig} account data. */
export function getRoleConfigDecoder(): FixedSizeDecoder<RoleConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mint", getAddressDecoder()],
    ["masterAuthority", getAddressDecoder()],
    ["pauser", getAddressDecoder()],
    ["burner", getAddressDecoder()],
    ["blacklister", getAddressDecoder()],
    ["seizer", getAddressDecoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link RoleConfig} account data. */
export function getRoleConfigCodec(): FixedSizeCodec<
  RoleConfigArgs,
  RoleConfig
> {
  return combineCodec(getRoleConfigEncoder(), getRoleConfigDecoder());
}

export function decodeRoleConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RoleConfig, TAddress>;
export function decodeRoleConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RoleConfig, TAddress>;
export function decodeRoleConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<RoleConfig, TAddress> | MaybeAccount<RoleConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRoleConfigDecoder(),
  );
}

export async function fetchRoleConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RoleConfig, TAddress>> {
  const maybeAccount = await fetchMaybeRoleConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRoleConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RoleConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRoleConfig(maybeAccount);
}

export async function fetchAllRoleConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<RoleConfig>[]> {
  const maybeAccounts = await fetchAllMaybeRoleConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRoleConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RoleConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeRoleConfig(maybeAccount));
}

export function getRoleConfigSize(): number {
  return 201;
}
