/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const STABLECOIN_CONFIG_DISCRIMINATOR = new Uint8Array([
  127, 25, 244, 213, 1, 192, 101, 6,
]);

export function getStablecoinConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    STABLECOIN_CONFIG_DISCRIMINATOR,
  );
}

export type StablecoinConfig = {
  discriminator: ReadonlyUint8Array;
  mint: Address;
  authority: Address;
  name: string;
  symbol: string;
  uri: string;
  decimals: number;
  enablePermanentDelegate: boolean;
  enableTransferHook: boolean;
  defaultAccountFrozen: boolean;
  paused: boolean;
  totalMinted: bigint;
  totalBurned: bigint;
  createdAt: bigint;
  lastChangedBy: Address;
  lastChangedAt: bigint;
  bump: number;
};

export type StablecoinConfigArgs = {
  mint: Address;
  authority: Address;
  name: string;
  symbol: string;
  uri: string;
  decimals: number;
  enablePermanentDelegate: boolean;
  enableTransferHook: boolean;
  defaultAccountFrozen: boolean;
  paused: boolean;
  totalMinted: number | bigint;
  totalBurned: number | bigint;
  createdAt: number | bigint;
  lastChangedBy: Address;
  lastChangedAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link StablecoinConfigArgs} account data. */
export function getStablecoinConfigEncoder(): Encoder<StablecoinConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mint", getAddressEncoder()],
      ["authority", getAddressEncoder()],
      ["name", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["symbol", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["uri", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["decimals", getU8Encoder()],
      ["enablePermanentDelegate", getBooleanEncoder()],
      ["enableTransferHook", getBooleanEncoder()],
      ["defaultAccountFrozen", getBooleanEncoder()],
      ["paused", getBooleanEncoder()],
      ["totalMinted", getU64Encoder()],
      ["totalBurned", getU64Encoder()],
      ["createdAt", getI64Encoder()],
      ["lastChangedBy", getAddressEncoder()],
      ["lastChangedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STABLECOIN_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link StablecoinConfig} account data. */
export function getStablecoinConfigDecoder(): Decoder<StablecoinConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mint", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["name", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["symbol", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["uri", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["decimals", getU8Decoder()],
    ["enablePermanentDelegate", getBooleanDecoder()],
    ["enableTransferHook", getBooleanDecoder()],
    ["defaultAccountFrozen", getBooleanDecoder()],
    ["paused", getBooleanDecoder()],
    ["totalMinted", getU64Decoder()],
    ["totalBurned", getU64Decoder()],
    ["createdAt", getI64Decoder()],
    ["lastChangedBy", getAddressDecoder()],
    ["lastChangedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link StablecoinConfig} account data. */
export function getStablecoinConfigCodec(): Codec<
  StablecoinConfigArgs,
  StablecoinConfig
> {
  return combineCodec(
    getStablecoinConfigEncoder(),
    getStablecoinConfigDecoder(),
  );
}

export function decodeStablecoinConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<StablecoinConfig, TAddress>;
export function decodeStablecoinConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<StablecoinConfig, TAddress>;
export function decodeStablecoinConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<StablecoinConfig, TAddress>
  | MaybeAccount<StablecoinConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getStablecoinConfigDecoder(),
  );
}

export async function fetchStablecoinConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<StablecoinConfig, TAddress>> {
  const maybeAccount = await fetchMaybeStablecoinConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeStablecoinConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<StablecoinConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeStablecoinConfig(maybeAccount);
}

export async function fetchAllStablecoinConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<StablecoinConfig>[]> {
  const maybeAccounts = await fetchAllMaybeStablecoinConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeStablecoinConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<StablecoinConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeStablecoinConfig(maybeAccount),
  );
}
