//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct StablecoinDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("2MKyZ3ugkGyfConZAsqm3hwRoY6c2k7zwZaX1XCSHsJH");

pub mod compatibility;
pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
