/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";

export const INITIALIZE_EXTRA_ACCOUNT_META_LIST_DISCRIMINATOR = new Uint8Array([
  43, 34, 13, 49, 167, 88, 235, 235,
]);

export function getInitializeExtraAccountMetaListDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_EXTRA_ACCOUNT_META_LIST_DISCRIMINATOR,
  );
}

export type InitializeExtraAccountMetaListInstruction<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountExtraAccountMetaList extends string
        ? WritableAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeExtraAccountMetaListInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type InitializeExtraAccountMetaListInstructionDataArgs = {};

export function getInitializeExtraAccountMetaListInstructionDataEncoder(): FixedSizeEncoder<InitializeExtraAccountMetaListInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_EXTRA_ACCOUNT_META_LIST_DISCRIMINATOR,
    }),
  );
}

export function getInitializeExtraAccountMetaListInstructionDataDecoder(): FixedSizeDecoder<InitializeExtraAccountMetaListInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getInitializeExtraAccountMetaListInstructionDataCodec(): FixedSizeCodec<
  InitializeExtraAccountMetaListInstructionDataArgs,
  InitializeExtraAccountMetaListInstructionData
> {
  return combineCodec(
    getInitializeExtraAccountMetaListInstructionDataEncoder(),
    getInitializeExtraAccountMetaListInstructionDataDecoder(),
  );
}

export type InitializeExtraAccountMetaListAsyncInput<
  TAccountPayer extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  extraAccountMetaList?: Address<TAccountExtraAccountMetaList>;
  mint: Address<TAccountMint>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getInitializeExtraAccountMetaListInstructionAsync<
  TAccountPayer extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: InitializeExtraAccountMetaListAsyncInput<
    TAccountPayer,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeExtraAccountMetaListInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.extraAccountMetaList.value) {
    accounts.extraAccountMetaList.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            101, 120, 116, 114, 97, 45, 97, 99, 99, 111, 117, 110, 116, 45, 109,
            101, 116, 97, 115,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitializeExtraAccountMetaListInstructionDataEncoder().encode({}),
    programAddress,
  } as InitializeExtraAccountMetaListInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountSystemProgram
  >);
}

export type InitializeExtraAccountMetaListInput<
  TAccountPayer extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  mint: Address<TAccountMint>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getInitializeExtraAccountMetaListInstruction<
  TAccountPayer extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: InitializeExtraAccountMetaListInput<
    TAccountPayer,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeExtraAccountMetaListInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountExtraAccountMetaList,
  TAccountMint,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitializeExtraAccountMetaListInstructionDataEncoder().encode({}),
    programAddress,
  } as InitializeExtraAccountMetaListInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeExtraAccountMetaListInstruction<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    extraAccountMetaList: TAccountMetas[1];
    mint: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeExtraAccountMetaListInstructionData;
};

export function parseInitializeExtraAccountMetaListInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeExtraAccountMetaListInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      mint: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeExtraAccountMetaListInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
