//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use crate::compatibility::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AddToBlacklist {
    pub reason: String,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AddToBlacklistInstructionAccounts {
    pub authority: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub role_config: solana_pubkey::Pubkey,
    pub wallet: solana_pubkey::Pubkey,
    pub blacklist_entry: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AddToBlacklist {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[90, 115, 98, 231, 173, 119, 117, 176] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for AddToBlacklist {
    type ArrangedAccounts = AddToBlacklistInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let role_config = next_account(&mut iter)?;
        let wallet = next_account(&mut iter)?;
        let blacklist_entry = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AddToBlacklistInstructionAccounts {
            authority,
            config,
            role_config,
            wallet,
            blacklist_entry,
            system_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
