//! This code was AUTOGENERATED using the Codama library.

use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
pub use super::super::events;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, carbon_core::borsh::BorshSerialize, carbon_core::borsh::BorshDeserialize, PartialEq)]
pub enum CpiEvent {
    AccountFrozen(events::account_frozen::AccountFrozenEvent),
    AccountThawed(events::account_thawed::AccountThawedEvent),
    AddressBlacklisted(events::address_blacklisted::AddressBlacklistedEvent),
    AddressUnblacklisted(events::address_unblacklisted::AddressUnblacklistedEvent),
    AuthorityTransferred(events::authority_transferred::AuthorityTransferredEvent),
    MinterUpdated(events::minter_updated::MinterUpdatedEvent),
    PauseChanged(events::pause_changed::PauseChangedEvent),
    RolesUpdated(events::roles_updated::RolesUpdatedEvent),
    StablecoinInitialized(events::stablecoin_initialized::StablecoinInitializedEvent),
    TokensBurned(events::tokens_burned::TokensBurnedEvent),
    TokensMinted(events::tokens_minted::TokensMintedEvent),
    TokensSeized(events::tokens_seized::TokensSeizedEvent),
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CpiEventInstructionAccounts {
    pub program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CpiEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[228, 69, 165, 46, 81, 203, 154, 29] {
            return None;
        }

        let event_data = &data[8..];

                if let Some(decoded) = events::account_frozen::AccountFrozenEvent::decode(event_data) {
            return Some(CpiEvent::AccountFrozen(decoded));
        }
                if let Some(decoded) = events::account_thawed::AccountThawedEvent::decode(event_data) {
            return Some(CpiEvent::AccountThawed(decoded));
        }
                if let Some(decoded) = events::address_blacklisted::AddressBlacklistedEvent::decode(event_data) {
            return Some(CpiEvent::AddressBlacklisted(decoded));
        }
                if let Some(decoded) = events::address_unblacklisted::AddressUnblacklistedEvent::decode(event_data) {
            return Some(CpiEvent::AddressUnblacklisted(decoded));
        }
                if let Some(decoded) = events::authority_transferred::AuthorityTransferredEvent::decode(event_data) {
            return Some(CpiEvent::AuthorityTransferred(decoded));
        }
                if let Some(decoded) = events::minter_updated::MinterUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::MinterUpdated(decoded));
        }
                if let Some(decoded) = events::pause_changed::PauseChangedEvent::decode(event_data) {
            return Some(CpiEvent::PauseChanged(decoded));
        }
                if let Some(decoded) = events::roles_updated::RolesUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::RolesUpdated(decoded));
        }
                if let Some(decoded) = events::stablecoin_initialized::StablecoinInitializedEvent::decode(event_data) {
            return Some(CpiEvent::StablecoinInitialized(decoded));
        }
                if let Some(decoded) = events::tokens_burned::TokensBurnedEvent::decode(event_data) {
            return Some(CpiEvent::TokensBurned(decoded));
        }
                if let Some(decoded) = events::tokens_minted::TokensMintedEvent::decode(event_data) {
            return Some(CpiEvent::TokensMinted(decoded));
        }
                if let Some(decoded) = events::tokens_seized::TokensSeizedEvent::decode(event_data) {
            return Some(CpiEvent::TokensSeized(decoded));
        }
                None
    }
}

impl ArrangeAccounts for CpiEvent {
    type ArrangedAccounts = CpiEventInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let [program, event_authority, remaining @ ..] = accounts else {
            return None;
        };

        Some(CpiEventInstructionAccounts {
            program: program.pubkey,
            event_authority: event_authority.pubkey,
            remaining: remaining.to_vec(),
        })
    }
}

