//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use crate::compatibility::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::InitializeParams;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Initialize {
    pub params: InitializeParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializeInstructionAccounts {
    pub authority: solana_pubkey::Pubkey,
    pub mint: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub role_config: solana_pubkey::Pubkey,
    pub extra_account_meta_list: Option<solana_pubkey::Pubkey>,
    pub transfer_hook_program: Option<solana_pubkey::Pubkey>,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Initialize {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[175, 175, 109, 31, 13, 152, 155, 237] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for Initialize {
    type ArrangedAccounts = InitializeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority = next_account(&mut iter)?;
        let mint = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let role_config = next_account(&mut iter)?;
        let extra_account_meta_list = next_account(&mut iter);
        let transfer_hook_program = next_account(&mut iter);
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitializeInstructionAccounts {
            authority,
            mint,
            config,
            role_config,
            extra_account_meta_list,
            transfer_hook_program,
            token_program,
            system_program,
            rent,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
