//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::StablecoinDecoder;


pub mod add_to_blacklist;
pub mod burn;
pub mod freeze_account;
pub mod initialize;
pub mod mint;
pub mod pause;
pub mod remove_from_blacklist;
pub mod seize;
pub mod thaw_account;
pub mod transfer_authority;
pub mod unpause;
pub mod update_minter;
pub mod update_roles;
pub mod cpi_event;

pub use self::add_to_blacklist::*;
pub use self::burn::*;
pub use self::freeze_account::*;
pub use self::initialize::*;
pub use self::mint::*;
pub use self::pause::*;
pub use self::remove_from_blacklist::*;
pub use self::seize::*;
pub use self::thaw_account::*;
pub use self::transfer_authority::*;
pub use self::unpause::*;
pub use self::update_minter::*;
pub use self::update_roles::*;
pub use self::cpi_event::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum StablecoinInstruction {
    AddToBlacklist(AddToBlacklist),
    Burn(Burn),
    FreezeAccount(FreezeAccount),
    Initialize(Initialize),
    Mint(Mint),
    Pause(Pause),
    RemoveFromBlacklist(RemoveFromBlacklist),
    Seize(Seize),
    ThawAccount(ThawAccount),
    TransferAuthority(TransferAuthority),
    Unpause(Unpause),
    UpdateMinter(UpdateMinter),
    UpdateRoles(UpdateRoles),
    // Anchor CPI Event Instruction
    CpiEvent(CpiEvent)
}

impl carbon_core::instruction::InstructionDecoder<'_> for StablecoinDecoder {
    type InstructionType = StablecoinInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = add_to_blacklist::AddToBlacklist::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::AddToBlacklist(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = burn::Burn::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Burn(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = freeze_account::FreezeAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::FreezeAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = mint::Mint::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Mint(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = pause::Pause::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Pause(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_from_blacklist::RemoveFromBlacklist::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::RemoveFromBlacklist(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = seize::Seize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Seize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = thaw_account::ThawAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::ThawAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = transfer_authority::TransferAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::TransferAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = unpause::Unpause::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::Unpause(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_minter::UpdateMinter::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::UpdateMinter(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_roles::UpdateRoles::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::UpdateRoles(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: StablecoinInstruction::CpiEvent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
