//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use crate::compatibility::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Seize {
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SeizeInstructionAccounts {
    pub authority: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub role_config: solana_pubkey::Pubkey,
    pub mint: solana_pubkey::Pubkey,
    pub from: solana_pubkey::Pubkey,
    pub to: solana_pubkey::Pubkey,
    pub blacklist_entry: solana_pubkey::Pubkey,
    pub stablecoin_program: solana_pubkey::Pubkey,
    pub transfer_hook_program: solana_pubkey::Pubkey,
    pub extra_account_meta_list: solana_pubkey::Pubkey,
    pub destination_blacklist: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Seize {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[129, 159, 143, 31, 161, 224, 241, 84] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for Seize {
    type ArrangedAccounts = SeizeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let role_config = next_account(&mut iter)?;
        let mint = next_account(&mut iter)?;
        let from = next_account(&mut iter)?;
        let to = next_account(&mut iter)?;
        let blacklist_entry = next_account(&mut iter)?;
        let stablecoin_program = next_account(&mut iter)?;
        let transfer_hook_program = next_account(&mut iter)?;
        let extra_account_meta_list = next_account(&mut iter)?;
        let destination_blacklist = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(SeizeInstructionAccounts {
            authority,
            config,
            role_config,
            mint,
            from,
            to,
            blacklist_entry,
            stablecoin_program,
            transfer_hook_program,
            extra_account_meta_list,
            destination_blacklist,
            token_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
